development:
  adapter: postgresql
  encoding: unicode
  database: auth_service_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: auth_service_test
  pool: 5
  username: postgres
  password: postgres
